//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the tool..
//    Runtime version: 4.0.30319.42000
//
//     Modifications to this file may cause inappropriate behavior and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaufortCipher.Properties
{


    /// <summary>
    ///   A strongly typed resource class for searching for localized strings, etc..
    /// </summary>
    // This class was automatically generated using the StronglyTypedResourceBuilder class
    // by a tool such as  Visual Studio.
    // To add or remove members, edit the ResX file, then run ResGen again
    // with the / str option or recompile the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns a cached instance of the ResourceManager component used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp_SzyfrowanieBeauforta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the CurrentUICulture property of the current thread to everyone
        ///   resource search cases with this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
